### ISSUE TITLE
Lua throws error if built in Release mode

### ISSUE THREAD

**Issue by phanhoang1366** [LDAsuku/soggy#10]
#### Description
The server will build and run normally if built in Release mode (the dispatch server also works), but as soon as I click "Press to enter" in the game, the server crashes with `PANIC: unprotected error in call to Lua API (attempt to index a nil value)`

https://user-images.githubusercontent.com/84622359/209133655-d45d7623-0cbc-4f88-860e-aecbc4a09bf6.mp4

#### Reproduce
Build the executable in Release mode (on Linux, add `-DCMAKE_BUILD_TYPE="Release"` in the setup step, or choose "Release" in Visual Studio on Windows and build normally) and attempt to enter the game.

**Comment by kobacat** [comment]
currently having the same problem using the same method, the executable also half the time doesn't boot properly, but when it does, the same Lua error occurs either way

**Comment by phanhoang1366** [comment]
Upon debugging, I noticed that it was failing on line 432:
```
(gdb) s
soglua_set_int (i=0, key=0x5555557e20d0 "Default", L=0x7ffff008b478)
    at /home/arc/soggy/src/game_data.cpp:431
431             lua_pushinteger(L, i);
(gdb) s
432             lua_setfield(L, -2, key);
(gdb) p key
$1 = 0x5555557e20d0 "Default"
(gdb) p L
$2 = (lua_State *) 0x7ffff008b478
(gdb) s
PANIC: unprotected error in call to Lua API (attempt to index a nil value)

Thread 2 "soggy" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
```
Here is a stack trace if needed:
```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6,
    no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff76a16b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>)
    at pthread_kill.c:78
#2  0x00007ffff7651958 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff763b53d in __GI_abort () at abort.c:79
#4  0x00007ffff7f73041 in ?? () from /usr/lib/liblua.so.5.4
#5  0x00007ffff7f7d8ed in ?? () from /usr/lib/liblua.so.5.4
#6  0x00007ffff7f7daab in ?? () from /usr/lib/liblua.so.5.4
#7  0x00007ffff7f7e1b4 in ?? () from /usr/lib/liblua.so.5.4
#8  0x00007ffff7f904b2 in ?? () from /usr/lib/liblua.so.5.4
#9  0x00007ffff7f7b26c in ?? () from /usr/lib/liblua.so.5.4
#10 0x0000555555600f3f in soglua_set_int (i=0, key=0x5555557e20d0 "Default", L=0x7ffff008b478)
    at /home/arc/soggy/src/game_data.cpp:432
#11 load_scene_script_data (sceneid=<optimized out>) at /home/arc/soggy/src/game_data.cpp:464
#12 0x00005555555f28ed in handle_PlayerLoginReq (conn=0x555555915f80 <mainconn>,
    playerloginreq=<optimized out>) at /home/arc/soggy/src/soggy.cpp:1232
#13 0x00005555555f5f33 in game_server_main () at /home/arc/soggy/src/soggy.cpp:1765
#14 0x00007ffff78d62f3 in std::execute_native_thread_routine (__p=0x555555ae6d00)
    at /usr/src/debug/gcc/libstdc++-v3/src/c++11/thread.cc:82
#15 0x00007ffff769f8fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#16 0x00007ffff7721a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
Maybe I will learn how to debug the Lua script in the future...

**Comment by phanhoang1366** [comment]
> currently having the same problem using the same method, the executable also half the time doesn't boot properly, but when it does, the same Lua error occurs either way

Seems like the "not booting properly" cannot be reproduced on a Linux environment, only Windows.

**Comment by ASHILTINEC** [comment]
Same problem, I don't know how to fix it. Please HELP
